#include "ppc32_decode.h"
#include "arm64_emit.h"
#include "arm64_codegen.h"
#include "ir.h"
#include "regalloc.h"
#include "xex.h"

#include <cstdio>
#include <map>
#include <string>
#include <vector>

namespace {

struct Options {
    std::string input;
    std::string output = "out.s";
};

bool parse_args(int argc, char** argv, Options& o) {
    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        if (a == "-o" && i + 1 < argc) {
            o.output = argv[++i];
        } else if (a == "-h" || a == "--help") {
            return false;
        } else {
            o.input = a;
        }
    }
    return !o.input.empty();
}

void print_usage() {
    std::printf("usage: real-steel-recomp default.xex [-o out.s]\n");
    std::printf("  Static recompiler foundation: XEX2 (PPC32) -> ARM64 assembly.\n");
}

uint64_t fetch(const rsr::XexImage& img, const rsr::XexSection& sec, uint64_t addr) {
    uint64_t size = uint64_t(sec.page_size) * sec.page_count;
    if (addr < sec.vaddr || addr >= sec.vaddr + size) return 0;
    uint64_t file = sec.data_offset + (addr - sec.vaddr);
    if (file + 4 > img.data.size()) return 0;
    return rsr::be32(img.data.data() + file);
}

} // namespace

int main(int argc, char** argv) {
    Options o;
    if (!parse_args(argc, argv, o)) {
        print_usage();
        return 1;
    }

    rsr::XexImage img = rsr::load_xex(o.input);
    if (!img.ok) {
        std::fprintf(stderr, "error: %s\n", img.error.c_str());
        return 1;
    }

    const rsr::XexSection* entry_sec = img.section_at(img.entry);
    if (!entry_sec) {
        std::fprintf(stderr, "error: entry point 0x%llx is not inside any section\n",
                     (unsigned long long)img.entry);
        return 1;
    }

    uint64_t size = uint64_t(entry_sec->page_size) * entry_sec->page_count;
    std::printf("xex: base=0x%llx entry=0x%llx image=%llu bytes file=%zu bytes\n",
                (unsigned long long)img.base,
                (unsigned long long)img.entry,
                (unsigned long long)img.image_size,
                img.data.size());
    std::printf("text section at 0x%llx (%llu bytes, %u pages x %u bytes)\n",
                (unsigned long long)entry_sec->vaddr,
                (unsigned long long)size,
                entry_sec->page_count, entry_sec->page_size);

    // Pass 1: decode to collect branch targets + function boundaries (bl).
    std::map<uint64_t, bool> labels;
    std::map<uint64_t, bool> functions;
    std::vector<rsr::Insn> insns;
    uint64_t unsupported = 0;
    for (uint64_t pc = entry_sec->vaddr; pc + 4 <= entry_sec->vaddr + size; pc += 4) {
        uint32_t w = static_cast<uint32_t>(fetch(img, *entry_sec, pc));
        rsr::Insn in = rsr::decode(w, pc);
        insns.push_back(in);
        if (in.op == rsr::Op::UNKNOWN) unsupported++;
        if (in.op == rsr::Op::B || in.op == rsr::Op::BL) {
            uint64_t target = in.aa ? (in.d & 0xFFFFFFFF) : (pc + in.d);
            labels[target] = true;
        } else if (in.op == rsr::Op::BC) {
            uint64_t target = pc + in.d;
            labels[target] = true;
        }
        int64_t ct = rsr::call_target(in);
        if (ct >= 0 && img.section_at(ct)) functions[static_cast<uint64_t>(ct)] = true;
    }
    std::printf("decoded %zu insns, %zu unsupported, %zu function starts\n",
                insns.size(), unsupported, functions.size());

    FILE* out = std::fopen(o.output.c_str(), "w");
    if (!out) {
        std::fprintf(stderr, "error: cannot open output %s\n", o.output.c_str());
        return 1;
    }

    std::fprintf(out, "// Generated by real-steel-recomp (XEX2/PPC32 -> ARM64)\n");
    std::fprintf(out, "// Source: %s  entry=0x%llx\n", o.input.c_str(), (unsigned long long)img.entry);
    std::fprintf(out, ".text\n.align 2\n.globl entry\nentry:\n");
    for (const auto& in : insns) {
        auto fit = functions.find(in.pc);
        if (fit != functions.end())
            std::fprintf(out, "L_%llx: /* fn */\n", (unsigned long long)in.pc);
        auto it = labels.find(in.pc);
        if (it != labels.end())
            std::fprintf(out, "L_%llx:\n", (unsigned long long)in.pc);
        std::string target;
        if (in.op == rsr::Op::B || in.op == rsr::Op::BL) {
            char lbl[32];
            std::snprintf(lbl, sizeof(lbl), "L_%llx", (unsigned long long)(in.aa ? (in.d & 0xFFFFFFFF) : (in.pc + in.d)));
            if (labels.count(in.aa ? (in.d & 0xFFFFFFFF) : (in.pc + in.d)))
                target = lbl;
        } else if (in.op == rsr::Op::BC) {
            char lbl[32];
            std::snprintf(lbl, sizeof(lbl), "L_%llx", (unsigned long long)(in.pc + in.d));
            if (labels.count(in.pc + in.d)) target = lbl;
        }
        std::fprintf(out, "  /* %08llx: */ %s\n",
                     (unsigned long long)in.pc, rsr::emit_arm64(in, target).c_str());
    }
    std::fclose(out);

    // IR + regalloc + codegen pass (whole-section function model: entry and
    // all bl targets get a function whose extent ends at the next start).
    std::vector<uint64_t> fns;
    fns.push_back(entry_sec->vaddr);
    for (const auto& kv : functions) fns.push_back(kv.first);
    std::sort(fns.begin(), fns.end());
    fns.erase(std::unique(fns.begin(), fns.end()), fns.end());
    // Entry is at the top; only include addresses inside this section.
    std::vector<uint64_t> starts;
    for (uint64_t a : fns)
        if (a >= entry_sec->vaddr && a < entry_sec->vaddr + size) starts.push_back(a);

    auto in_range_check = [](uint64_t addr, void* ctx) -> bool {
        auto* sections = static_cast<std::vector<std::pair<uint64_t, uint64_t>>*>(ctx);
        for (const auto& s : *sections)
            if (addr >= s.first && addr < s.second) return true;
        return false;
    };
    std::vector<std::pair<uint64_t, uint64_t>> sections = {{entry_sec->vaddr, entry_sec->vaddr + size}};

    FILE* ir_out = std::fopen((o.output + ".ir").c_str(), "w");
    if (ir_out) {
        std::fprintf(ir_out, "// IR + regalloc + ARM64 codegen for %s\n", o.input.c_str());
        size_t total_blocks = 0, total_vregs = 0, spilled = 0, unsup = 0;
        for (size_t i = 0; i < starts.size(); i++) {
            uint64_t end = (i + 1 < starts.size()) ? starts[i + 1] : entry_sec->vaddr + size;
            std::vector<uint64_t> callees;
            rsr::IRFunc f = rsr::build_ir(insns, starts[i], end, callees);
            rsr::RegAlloc ra = rsr::linear_scan(f, 16);
            for (int s : ra.slot) if (s >= 0) spilled++;
            for (int p : ra.phys) if (p >= 0) total_vregs++;
            for (const auto& b : f.blocks) {
                total_blocks++;
                for (const auto& ir : b.insns) if (ir.op == rsr::IROp::UNSUP) unsup++;
            }
            std::string ir_text = rsr::ir_to_string(f);
            std::string ra_text = rsr::regalloc_to_string(f, ra);
            std::string asm_text = rsr::codegen_arm64(f, ra, in_range_check, &sections);
            std::fprintf(ir_out, "%s%s%s\n", ir_text.c_str(), ra_text.c_str(), asm_text.c_str());
        }
        std::fclose(ir_out);
        std::printf("IR pass: %zu functions, %zu blocks, %zu live vregs, %zu spills, %zu unsupported ir\n",
                    starts.size(), total_blocks, total_vregs, spilled, unsup);
    }
    std::printf("wrote %s (%zu instructions); IR report -> %s.ir\n",
                o.output.c_str(), insns.size(), o.output.c_str());
    return 0;
}